<?php
declare(strict_types=1);
require_once __DIR__ . '/data.php';
[$user,$demo]=manager_access();
$db=app_db();$stats=manager_stats($db,$demo);
$months=[];
for($i=5;$i>=0;$i--){$date=new DateTimeImmutable('first day of this month',new DateTimeZone('UTC'));$date=$date->modify('-'.$i.' months');$months[$date->format('Y-m')]=['label'=>$date->format('M Y'),'amount'=>0];}
if($demo){$samples=[24000,38500,47000,52000,69000,92500];$j=0;foreach($months as &$month)$month['amount']=$samples[$j++];unset($month);$transactions=[['paid_at'=>'2026-10-08','email'=>'amina.kariuki@example.com','amount_subunit'=>250000,'currency_code'=>'KES'],['paid_at'=>'2026-10-07','email'=>'daniel.okoro@example.com','amount_subunit'=>100000,'currency_code'=>'KES']];}
else {
    $q=$db->query("SELECT DATE_FORMAT(paid_at,'%Y-%m') AS month,SUM(amount_subunit)/100 AS amount FROM seller_plan_charges WHERE currency_code='KES' AND paid_at>=DATE_FORMAT(UTC_TIMESTAMP() - INTERVAL 5 MONTH,'%Y-%m-01') GROUP BY DATE_FORMAT(paid_at,'%Y-%m')");
    foreach($q as $row)if(isset($months[$row['month']]))$months[$row['month']]['amount']=(float)$row['amount'];
    $transactions=$db->query("SELECT c.paid_at,u.email,c.amount_subunit,c.currency_code FROM seller_plan_charges c JOIN users u ON u.id=c.user_id ORDER BY c.paid_at DESC LIMIT 10")->fetchAll();
}
$max=max(1,...array_column($months,'amount'));
manager_header('Revenue','revenue',$user,$demo);
?><div class="manager-heading"><div><span class="manager-eyebrow">PAYMENTS</span><h1>Revenue</h1><p>Confirmed seller plan payments recorded by Paystack.</p></div></div><div class="manager-metrics manager-metrics-two"><div class="manager-metric manager-metric-revenue"><span>Lifetime collected</span><strong>KSh <?= number_format($stats['revenue']) ?></strong><small>KES payments recorded</small></div><div class="manager-metric"><span>Collected this month</span><strong>KSh <?= number_format($stats['this_month']) ?></strong><small>Since the first day of this month</small></div></div><section class="manager-panel"><div class="manager-section-head"><div><span class="manager-eyebrow">PERFORMANCE</span><h2>Monthly revenue</h2></div><small>Last 6 months · KES</small></div><div class="manager-chart" role="img" aria-label="Monthly revenue for the last six months"><?php foreach($months as $month): ?><div class="manager-chart-col"><strong>KSh <?= number_format($month['amount']) ?></strong><span style="height:<?= max(4,round($month['amount']/$max*100)) ?>%"></span><small><?= app_h($month['label']) ?></small></div><?php endforeach; ?></div></section><section class="manager-panel"><div class="manager-section-head"><div><span class="manager-eyebrow">PAYMENT HISTORY</span><h2>Recent payments</h2></div></div><div class="manager-table-scroll"><table class="manager-table"><thead><tr><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach($transactions as $item): ?><tr><td><strong><?= app_h($item['email']) ?></strong></td><td><?= app_h(substr((string)$item['paid_at'],0,10)) ?></td><td><?= app_h($item['currency_code']) ?> <?= number_format((int)$item['amount_subunit']/100) ?></td><td><span class="manager-status manager-status-published">Confirmed</span></td></tr><?php endforeach; ?><?php if(!$transactions): ?><tr><td colspan="4">No payments recorded yet.</td></tr><?php endif; ?></tbody></table></div></section><?php manager_footer(); ?>
