<?php
declare(strict_types=1);

/** African countries and tender currency codes generated from installed CLDR data in October 2026. */
function marketplace_african_countries(): array {
    return [
        'DZ' => ['Algeria', 'DZD'],
        'AO' => ['Angola', 'AOA'],
        'BJ' => ['Benin', 'XOF'],
        'BW' => ['Botswana', 'BWP'],
        'BF' => ['Burkina Faso', 'XOF'],
        'BI' => ['Burundi', 'BIF'],
        'CV' => ['Cabo Verde', 'CVE'],
        'CM' => ['Cameroon', 'XAF'],
        'CF' => ['Central African Republic', 'XAF'],
        'TD' => ['Chad', 'XAF'],
        'KM' => ['Comoros', 'KMF'],
        'CG' => ['Congo', 'XAF'],
        'CI' => ['Côte d’Ivoire', 'XOF'],
        'CD' => ['DR Congo', 'CDF'],
        'DJ' => ['Djibouti', 'DJF'],
        'EG' => ['Egypt', 'EGP'],
        'GQ' => ['Equatorial Guinea', 'XAF'],
        'ER' => ['Eritrea', 'ERN'],
        'SZ' => ['Eswatini', 'SZL'],
        'ET' => ['Ethiopia', 'ETB'],
        'GA' => ['Gabon', 'XAF'],
        'GM' => ['Gambia', 'GMD'],
        'GH' => ['Ghana', 'GHS'],
        'GN' => ['Guinea', 'GNF'],
        'GW' => ['Guinea-Bissau', 'XOF'],
        'KE' => ['Kenya', 'KES'],
        'LS' => ['Lesotho', 'LSL'],
        'LR' => ['Liberia', 'LRD'],
        'LY' => ['Libya', 'LYD'],
        'MG' => ['Madagascar', 'MGA'],
        'MW' => ['Malawi', 'MWK'],
        'ML' => ['Mali', 'XOF'],
        'MR' => ['Mauritania', 'MRU'],
        'MU' => ['Mauritius', 'MUR'],
        'MA' => ['Morocco', 'MAD'],
        'MZ' => ['Mozambique', 'MZN'],
        'NA' => ['Namibia', 'NAD'],
        'NE' => ['Niger', 'XOF'],
        'NG' => ['Nigeria', 'NGN'],
        'RW' => ['Rwanda', 'RWF'],
        'SN' => ['Senegal', 'XOF'],
        'SC' => ['Seychelles', 'SCR'],
        'SL' => ['Sierra Leone', 'SLE'],
        'SO' => ['Somalia', 'SOS'],
        'ZA' => ['South Africa', 'ZAR'],
        'SS' => ['South Sudan', 'SSP'],
        'SD' => ['Sudan', 'SDG'],
        'ST' => ['São Tomé and Príncipe', 'STN'],
        'TZ' => ['Tanzania', 'TZS'],
        'TG' => ['Togo', 'XOF'],
        'TN' => ['Tunisia', 'TND'],
        'UG' => ['Uganda', 'UGX'],
        'ZM' => ['Zambia', 'ZMW'],
        'ZW' => ['Zimbabwe', 'ZWG'],
    ];
}

function marketplace_currencies(): array {
    return [
        'AED' => 'United Arab Emirates Dirham',
        'AFN' => 'Afghan Afghani',
        'ALL' => 'Albanian Lek',
        'AMD' => 'Armenian Dram',
        'AOA' => 'Angolan Kwanza',
        'ARS' => 'Argentine Peso',
        'AUD' => 'Australian Dollar',
        'AWG' => 'Aruban Florin',
        'AZN' => 'Azerbaijani Manat',
        'BAM' => 'Bosnia-Herzegovina Convertible Mark',
        'BBD' => 'Barbadian Dollar',
        'BDT' => 'Bangladeshi Taka',
        'BGN' => 'Bulgarian Lev',
        'BHD' => 'Bahraini Dinar',
        'BIF' => 'Burundian Franc',
        'BMD' => 'Bermudan Dollar',
        'BND' => 'Brunei Dollar',
        'BOB' => 'Bolivian Boliviano',
        'BRL' => 'Brazilian Real',
        'BSD' => 'Bahamian Dollar',
        'BTN' => 'Bhutanese Ngultrum',
        'BWP' => 'Botswanan Pula',
        'BYN' => 'Belarusian Ruble',
        'BZD' => 'Belize Dollar',
        'CAD' => 'Canadian Dollar',
        'CDF' => 'Congolese Franc',
        'CHF' => 'Swiss Franc',
        'CLP' => 'Chilean Peso',
        'CNY' => 'Chinese Yuan',
        'COP' => 'Colombian Peso',
        'CRC' => 'Costa Rican Colón',
        'CUP' => 'Cuban Peso',
        'CVE' => 'Cape Verdean Escudo',
        'CZK' => 'Czech Koruna',
        'DJF' => 'Djiboutian Franc',
        'DKK' => 'Danish Krone',
        'DOP' => 'Dominican Peso',
        'DZD' => 'Algerian Dinar',
        'EGP' => 'Egyptian Pound',
        'ERN' => 'Eritrean Nakfa',
        'ETB' => 'Ethiopian Birr',
        'EUR' => 'Euro',
        'FJD' => 'Fijian Dollar',
        'FKP' => 'Falkland Islands Pound',
        'GBP' => 'British Pound',
        'GEL' => 'Georgian Lari',
        'GHS' => 'Ghanaian Cedi',
        'GIP' => 'Gibraltar Pound',
        'GMD' => 'Gambian Dalasi',
        'GNF' => 'Guinean Franc',
        'GTQ' => 'Guatemalan Quetzal',
        'GYD' => 'Guyanaese Dollar',
        'HKD' => 'Hong Kong Dollar',
        'HNL' => 'Honduran Lempira',
        'HTG' => 'Haitian Gourde',
        'HUF' => 'Hungarian Forint',
        'IDR' => 'Indonesian Rupiah',
        'ILS' => 'Israeli New Shekel',
        'INR' => 'Indian Rupee',
        'IQD' => 'Iraqi Dinar',
        'IRR' => 'Iranian Rial',
        'ISK' => 'Icelandic Króna',
        'JMD' => 'Jamaican Dollar',
        'JOD' => 'Jordanian Dinar',
        'JPY' => 'Japanese Yen',
        'KES' => 'Kenyan Shilling',
        'KGS' => 'Kyrgystani Som',
        'KHR' => 'Cambodian Riel',
        'KMF' => 'Comorian Franc',
        'KPW' => 'North Korean Won',
        'KRW' => 'South Korean Won',
        'KWD' => 'Kuwaiti Dinar',
        'KYD' => 'Cayman Islands Dollar',
        'KZT' => 'Kazakhstani Tenge',
        'LAK' => 'Laotian Kip',
        'LBP' => 'Lebanese Pound',
        'LKR' => 'Sri Lankan Rupee',
        'LRD' => 'Liberian Dollar',
        'LSL' => 'Lesotho Loti',
        'LYD' => 'Libyan Dinar',
        'MAD' => 'Moroccan Dirham',
        'MDL' => 'Moldovan Leu',
        'MGA' => 'Malagasy Ariary',
        'MKD' => 'Macedonian Denar',
        'MMK' => 'Myanmar Kyat',
        'MNT' => 'Mongolian Tugrik',
        'MOP' => 'Macanese Pataca',
        'MRU' => 'Mauritanian Ouguiya',
        'MUR' => 'Mauritian Rupee',
        'MVR' => 'Maldivian Rufiyaa',
        'MWK' => 'Malawian Kwacha',
        'MXN' => 'Mexican Peso',
        'MYR' => 'Malaysian Ringgit',
        'MZN' => 'Mozambican Metical',
        'NAD' => 'Namibian Dollar',
        'NGN' => 'Nigerian Naira',
        'NIO' => 'Nicaraguan Córdoba',
        'NOK' => 'Norwegian Krone',
        'NPR' => 'Nepalese Rupee',
        'NZD' => 'New Zealand Dollar',
        'OMR' => 'Omani Rial',
        'PAB' => 'Panamanian Balboa',
        'PEN' => 'Peruvian Sol',
        'PGK' => 'Papua New Guinean Kina',
        'PHP' => 'Philippine Peso',
        'PKR' => 'Pakistani Rupee',
        'PLN' => 'Polish Zloty',
        'PYG' => 'Paraguayan Guarani',
        'QAR' => 'Qatari Riyal',
        'RON' => 'Romanian Leu',
        'RSD' => 'Serbian Dinar',
        'RUB' => 'Russian Ruble',
        'RWF' => 'Rwandan Franc',
        'SAR' => 'Saudi Riyal',
        'SBD' => 'Solomon Islands Dollar',
        'SCR' => 'Seychellois Rupee',
        'SDG' => 'Sudanese Pound',
        'SEK' => 'Swedish Krona',
        'SGD' => 'Singapore Dollar',
        'SHP' => 'St. Helena Pound',
        'SLE' => 'Sierra Leonean Leone',
        'SOS' => 'Somali Shilling',
        'SRD' => 'Surinamese Dollar',
        'SSP' => 'South Sudanese Pound',
        'STN' => 'São Tomé & Príncipe Dobra',
        'SYP' => 'Syrian Pound',
        'SZL' => 'Swazi Lilangeni',
        'THB' => 'Thai Baht',
        'TJS' => 'Tajikistani Somoni',
        'TMT' => 'Turkmenistani Manat',
        'TND' => 'Tunisian Dinar',
        'TOP' => 'Tongan Paʻanga',
        'TRY' => 'Turkish Lira',
        'TTD' => 'Trinidad & Tobago Dollar',
        'TWD' => 'New Taiwan Dollar',
        'TZS' => 'Tanzanian Shilling',
        'UAH' => 'Ukrainian Hryvnia',
        'UGX' => 'Ugandan Shilling',
        'USD' => 'US Dollar',
        'UYU' => 'Uruguayan Peso',
        'UZS' => 'Uzbekistani Som',
        'VES' => 'Venezuelan Bolívar',
        'VND' => 'Vietnamese Dong',
        'VUV' => 'Vanuatu Vatu',
        'WST' => 'Samoan Tala',
        'XAF' => 'Central African CFA Franc',
        'XCD' => 'East Caribbean Dollar',
        'XCG' => 'Caribbean guilder',
        'XOF' => 'West African CFA Franc',
        'XPF' => 'CFP Franc',
        'YER' => 'Yemeni Rial',
        'ZAR' => 'South African Rand',
        'ZMW' => 'Zambian Kwacha',
        'ZWG' => 'Zimbabwean Gold',
    ];
}

function marketplace_country_name(?string $code): string {
    return marketplace_african_countries()[$code ?? ''][0] ?? '';
}

function marketplace_location_label(array $item): string {
    return implode(', ', array_filter([trim((string)($item['locality'] ?? '')), trim((string)($item['region'] ?? '')), marketplace_country_name($item['country_code'] ?? null)], static fn(string $value): bool => $value !== ''));
}

function marketplace_location_valid(string $country, string $region, string $locality): bool {
    return isset(marketplace_african_countries()[$country]) && mb_strlen($region) >= 2 && mb_strlen($region) <= 100 && mb_strlen($locality) >= 2 && mb_strlen($locality) <= 100;
}

function marketplace_currency_decimals(string $currency): int {
    if (!isset(marketplace_currencies()[$currency]) || !class_exists(NumberFormatter::class)) return 2;
    $formatter = new NumberFormatter('en', NumberFormatter::CURRENCY);
    $formatter->setTextAttribute(NumberFormatter::CURRENCY_CODE, $currency);
    return max(0, min(3, (int)$formatter->getAttribute(NumberFormatter::FRACTION_DIGITS)));
}

/** First-level places from Unicode CLDR; see CLDR-NOTICE.txt. */
function marketplace_country_regions(string $country): array {
    static $regions;
    if ($regions === null) $regions = json_decode((string)file_get_contents(__DIR__ . '/marketplace-regions.json'), true) ?: [];
    return $regions[$country] ?? [];
}
